### PR TITLE
chore: switch to yarn workspaces

### PR DESCRIPTION
**Pull request by willemneal**
Since lerna supports yarn workspaces this should speed up the initialization of the project, though adding a dependency of using yarn.

### CODE REVIEW

**Comment by willemneal** [comment]
Well I'm stumped why this isn't working.  @jtenner whenever you get a chance, could you test this out locally?

**Comment by jtenner** [comment]
Looks like the ci bootstrapping process doesn't link the modules correctly. Lame.

**Comment by jtenner** [comment]
Perhaps using yarn might be more effort than worth.

**Comment by jtenner** [comment]
Let's merge @MaxGraey's pull request first, then try this again.

**Pull request closed without merging**
